# Generated by Django 5.1.2 on 2024-10-16 05:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='refanimaltype',
            options={'verbose_name': 'Тип животного', 'verbose_name_plural': 'Типы животных'},
        ),
        migrations.AlterModelOptions(
            name='refbreed',
            options={'verbose_name': 'Порода', 'verbose_name_plural': 'Породы'},
        ),
        migrations.AlterModelOptions(
            name='weighting',
            options={'verbose_name': 'Взвешивание', 'verbose_name_plural': 'Взвешивания'},
        ),
        migrations.AlterField(
            model_name='animal',
            name='arrival_age',
            field=models.IntegerField(verbose_name='Возраст при прибытии'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='arrival_date',
            field=models.DateField(verbose_name='Дата прибытия'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='breed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.refbreed', verbose_name='Порода'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания записи'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='gender',
            field=models.CharField(choices=[('M', 'Самец'), ('F', 'Самка')], max_length=1, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='inventory_number',
            field=models.CharField(max_length=255, unique=True, verbose_name='Инвентарный номер'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='nickname_en',
            field=models.CharField(max_length=255, verbose_name='Кличка на английском'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='nickname_kk',
            field=models.CharField(max_length=255, verbose_name='Кличка на казахском'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='nickname_ru',
            field=models.CharField(max_length=255, verbose_name='Кличка на русском'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.animal', verbose_name='Родитель'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления записи'),
        ),
        migrations.AlterField(
            model_name='refanimaltype',
            name='name_en',
            field=models.CharField(max_length=255, verbose_name='Название на английском'),
        ),
        migrations.AlterField(
            model_name='refanimaltype',
            name='name_kk',
            field=models.CharField(max_length=255, verbose_name='Название на казахском'),
        ),
        migrations.AlterField(
            model_name='refanimaltype',
            name='name_ru',
            field=models.CharField(max_length=255, verbose_name='Название на русском'),
        ),
        migrations.AlterField(
            model_name='refbreed',
            name='name_en',
            field=models.CharField(max_length=255, verbose_name='Название на английском'),
        ),
        migrations.AlterField(
            model_name='refbreed',
            name='name_kk',
            field=models.CharField(max_length=255, verbose_name='Название на казахском'),
        ),
        migrations.AlterField(
            model_name='refbreed',
            name='name_ru',
            field=models.CharField(max_length=255, verbose_name='Название на русском'),
        ),
        migrations.AlterField(
            model_name='weighting',
            name='animal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.animal', verbose_name='Животное'),
        ),
        migrations.AlterField(
            model_name='weighting',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания записи'),
        ),
        migrations.AlterField(
            model_name='weighting',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления записи'),
        ),
        migrations.AlterField(
            model_name='weighting',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='weighting',
            name='weight',
            field=models.FloatField(verbose_name='Вес'),
        ),
        migrations.AlterField(
            model_name='weighting',
            name='weight_date',
            field=models.DateField(verbose_name='Дата взвешивания'),
        ),
    ]
