# Generated by Django 5.1.2 on 2024-10-16 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_refanimaltype_options_alter_refbreed_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animal',
            options={'verbose_name': 'Животное', 'verbose_name_plural': 'Животные'},
        ),
    ]
